export const FETCH_LIST_REQUEST = 'FETCH_LIST_REQUEST';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAILED = 'FETCH_LIST_FAILED';

export const CREATE_LIST_REQUEST = 'CREATE_LIST_REQUEST';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';
export const CREATE_LIST_FAILED = 'CREATE_LIST_FAILED';

export const DELETE_LIST_REQUEST = 'DELETE_LIST_REQUEST';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';
export const DELETE_LIST_FAILED = 'DELETE_LIST_FAILED';

export const ADD_MOVIE_TO_LIST_REQUEST = 'ADD_MOVIE_TO_LIST_REQUEST';
export const ADD_MOVIE_TO_LIST_SUCCESS = 'ADD_MOVIE_TO_LIST_SUCCESS';
export const ADD_MOVIE_TO_LIST_FAILED = 'ADD_MOVIE_TO_LIST_FAILED'; 

export const REMOVE_MOVIE_FROM_LIST_REQUEST = 'REMOVE_MOVIE_FROM_LIST_REQUEST';
export const REMOVE_MOVIE_FROM_LIST_SUCCESS = 'REMOVE_MOVIE_FROM_LIST_SUCCESS';
export const REMOVE_MOVIE_FROM_LIST_FAILED = 'REMOVE_MOVIE_FROM_LIST_FAILED'; 

export const CLEAR_LIST_REQUEST = 'CLEAR_LIST_REQUEST';
export const CLEAR_LIST_SUCCESS = 'CLEAR_LIST_SUCCESS';
export const CLEAR_LIST_FAILED = 'CLEAR_LIST_FAILED';




