export const FETCH_MOVIE_REQUEST = 'FETCH_MOVIE_REQUEST';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_FAILED = 'FETCH_MOVIE_FAILED';

export const RATE_MOVIE_SUCCESS = 'RATE_MOVIE_SUCCESS';
export const RATE_MOVIE_FAILED = 'RATE_MOVIE_FAILED';
