export const FETCH_SEASON_REQUEST = 'FETCH_SEASON_REQUEST';
export const FETCH_SEASON_SUCCESS = 'FETCH_SEASON_SUCCESS';
export const FETCH_SEASON_FAILED = 'FETCH_SEASON_FAILED';

export const RATE_EPISODE_SUCCESS = 'RATE_EPISODE_SUCCESS';
export const RATE_EPISODE_FAILED = 'RATE_EPISODE_FAILED';

export const REMOVE_EPISODE_RATING_SUCCESS = 'REMOVE_EPISODE_RATING_SUCCESS';
export const REMOVE_EPISODE_RATING_FAILED = 'REMOVE_EPISODE_RATING_FAILED';