export const FETCH_SHOW_REQUEST = 'FETCH_SHOW_REQUEST';
export const FETCH_SHOW_SUCCESS = 'FETCH_SHOW_SUCCESS';
export const FETCH_SHOW_FAILED = 'FETCH_SHOW_FAILED';

export const RATE_SHOW_OPTIMISTIC_REQUEST = 'RATE_SHOW_OPTIMISTIC_REQUEST';
export const RATE_SHOW_SUCCESS = 'RATE_SHOW_SUCCESS';
export const RATE_SHOW_FAILED = 'RATE_SHOW_FAILED';

export const REMOVE_SHOW_RATING_OPTIMISTIC_REQUEST = 'REMOVE_SHOW_RATING_OPTIMISTIC_REQUEST';
export const REMOVE_SHOW_RATING_SUCCESS = 'REMOVE_SHOW_RATING_SUCCESS';
export const REMOVE_SHOW_RATING_FAILED = 'REMOVE_SHOW_RATING_FAILED';