export const STORE_USER_SUMMARY = 'STORE_USER_SUMMARY';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const MARK_FAVOURITE_OPTIMISTIC_REQUEST = 'MARK_FAVOURITE_OPTIMISTIC_REQUEST';
export const MARK_FAVOURITE_SUCCESS = 'MARK_FAVOURITE_SUCCESS';
export const MARK_FAVOURITE_FAILED = 'MARK_FAVOURITE_FAILED';

export const EDIT_WATCHLIST_OPTIMISTIC_REQUEST = 'EDIT_WATCHLIST_OPTIMISTIC_REQUEST';
export const EDIT_WATCHLIST_SUCCESS = 'EDIT_WATCHLIST_SUCCESS';
export const EDIT_WATCHLIST_FAILED = 'EDIT_WATCHLIST_FAILED';

export const FETCH_FULL_PROFILE_REQUEST = 'FETCH_FULL_PROFILE_REQUEST';
export const FETCH_FULL_PROFILE_SUCCESS = 'FETCH_FULL_PROFILE_SUCCESS';
export const FETCH_FULL_PROFILE_FAILED = 'FETCH_FULL_PROFILE_FAILED';
